### ISSUE TITLE
how install psipred in Ubuntu 20.04 LTS?

### ISSUE THREAD

**Issue by biotech70** [psipred/psipred#6]
Hi. I try to install Psipred in ubuntu 20.04 LTS to make peptide fragments for rosetta but get the below error. Please guide me.
![psipred](https://user-images.githubusercontent.com/73783725/115950946-65641c80-a4f3-11eb-97e1-caff50ac5783.jpg)

**Comment by DanBuchan** [comment]
Probably you need to go in to the src directory and run

```
make clean
make
make install
```

I would also note that we don't consider PSIPRED accurate for secondary structure prediction on peptides shorted than 20 residues.

**Comment by biotech70** [comment]
These commands do not work either.
[error.txt](https://github.com/psipred/psipred/files/6426856/error.txt)

**Comment by DanBuchan** [comment]
I'm not sure what the issue is here. These appear to be compiler warnings. I just tried this on ubuntu 20.04 and the binaries were created. Do the binaries not get built for you?

**Comment by biotech70** [comment]
My operation system is Ubuntu 20.04 LTS

**Comment by DanBuchan** [comment]
I assume as you're asking further questions this is resolved

**Comment by biotech70** [comment]
No, the problem still exists. I installed the PSIPRED tool with CONDA, and instead of the runpsipred, there is  run_psipred.pl. please guide me.

**Comment by DanBuchan** [comment]
We do not support PSIPRED via conda. We have no idea who built that or whether they keep the package up to date.

Please clone this repo

**Comment by biotech70** [comment]
I install PSIPRED by below command because i cant install PSIPRED due to mentioned error.
conda install -c biocore psipred

**Comment by DanBuchan** [comment]
You're on your own with conda. We can only support installation from this repo or from the identical tarball on our website.

As I asked above, your screenshot and text file show only compiler warnings. I don't see that compilation failed from what you have provided. When you run `make` do new binaries get created? If new binaries are present then there is no problem here.

Is the problem you are having that there are no new binaries after you have run make?

1. Confirm the timestamps on the binaries in the `/bin` and `/src` directories
2. Run the installation commands

```
make clean
make
make install
```
3. Confirm again the new/updated timestamps on the binaries in the `/bin` and `/src` directories. 

If the timestamps are updated them compilation has been successful. I am using ubuntu 20.04 and gcc 9.3.0 and these steps were successful for me.
